### ISSUE TITLE
Cannot italicize text

### ISSUE THREAD

**Issue by WritwikRay** [getzola/after-dark#34]
_italicized_ does not produce an italicized text.

**Comment by apiraino** [comment]
@WritwikRay The following diff fixes the issue but I don't know if it's too invasive to qualify for a PR. Surely it would nice to be fixed :)

@Keats: the culprit CSS comes from the original `hack` [CSS file](https://codeberg.org/vhs/after-dark/src/branch/trunk/assets/css/vendor/hack/hack.css). Can it be removed in your opinion?


```diff
diff --git a/sass/_vendor.scss b/sass/_vendor.scss
index 778e900..ec15a41 100644
--- a/sass/_vendor.scss
+++ b/sass/_vendor.scss
@@ -177,7 +177,7 @@ a:hover {
   }
 }
 
-.hack, .hack blockquote, .hack code, .hack em, .hack h1, .hack h2, .hack h3, .hack h4, .hack h5, .hack h6, .hack strong {
+.hack, .hack blockquote, .hack code, .hack h1, .hack h2, .hack h3, .hack h4, .hack h5, .hack h6, .hack strong {
   font-size: 1rem;
   font-style: normal;
   font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif
@@ -282,11 +282,6 @@ a:hover {
   line-height: 20px
 }
 
-.hack em:after, .hack em:before {
-  content: "*";
-  display: inline
-}
-
 .hack pre code:after, .hack pre code:before {
   content: none
 }
```

**Comment by Keats** [comment]
That's how the theme looks like, there's nothing to fix. You can override it in some custom CSS though.

**Comment by apiraino** [comment]
> That's how the theme looks like, there's nothing to fix. You can override it in some custom CSS though.

well, imo this is a bug.

I'm not sure the original intent of the Hugo theme was to render italics like in the IRC heydays (example `*italics*` instead of _italics_). Even its [demo page](https://vhs.codeberg.page/after-dark/) renders italics as expected.

Or am I missing something?

**Comment by apiraino** [comment]
`*sigh*` ... understood. On with another custom CSS rule :)

thanks
